format_version: 10
pipelines:
  june-11-pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      phil:
        git: https://github.com/philhub85/vagrant-6322.git
        username: philhub85
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:SQsSZ7fUtlpWZS6STeRdEw==:icoVns6SmCn8+zRfmo6nbw==
    stages:
    - test-report:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-tests:
            timeout: 0
            tasks:
            - exec:
                command: enter
                run_if: passed
